spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev   #开发环境
  application:
    name: exam-consumer-config-dev
    
    server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: false

feign:
  hystrix:
    enable: true     #开启feign的hystrix支持,默认是false
---
server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: false

feign:
  hystrix:
    enable: true     #开启feign的hystrix支持,默认是false
    
spring:
  profiles: test  #测试环境
  application:  
    name: exam-consumer-config-test
    
#   请保存为UTF-8格式
